modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="createfa" #mandatory
version="1.0.7" #mandatory
displayName="CreateFoodAdditions" #mandatory
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="StacheGamer1609" #optional
description='''
A mod, which adds a lot of Food to Create!
'''
[[dependencies.createfa]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createfa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createfa]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2g,)"
    ordering="NONE"
    side="BOTH"