modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="createfa" #mandatory
version="1.0.8" #mandatory
displayName="CreateFoodAdditions" #mandatory
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="StacheGamer1609" #optional
description='''
A mod, adding a lot of Food to Create!
'''
[[dependencies.createfa]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.createfa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createfa]]
    modId="create"
    mandatory=true
    versionRange="[0.4a,)"
    ordering="NONE"
    side="BOTH"